export const ActionTypes = {
  SET_PRODUCTS_JEWERELY: "SET_PRODUCTS_JEWERELY",
  SET_PRODUCTS_ELECTRONIC: "SET_PRODUCTS_ELECTRONIC",
  SET_PRODUCTS_MENCLOTHING: "SET_PRODUCTS_MENCLOTHING",
  SET_PRODUCTS_WOMENCLOTHING: "SET_PRODUCTS_WOMENCLOTHING",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART:"ADD_TO_CART"
};
