export const ActionTypes = {
  SET_PRODUCTS_JEWERELY: "SET_PRODUCTS_JEWERELY",
  SET_PRODUCTS_ELECTRONIC: "SET_PRODUCTS_ELECTRONIC",
  SET_PRODUCTS_MENCLOTHING: "SET_PRODUCTS_MENCLOTHING",
  SET_PRODUCTS_WOMENCLOTHING: "SET_PRODUCTS_WOMENCLOTHING",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
};
