export const ActionTypes = {
  SET_PRODUCTS_JEWERELY: "SET_PRODUCTS_JEWERELY",
  SET_PRODUCTS_ELECTRONIC: "SET_PRODUCTS_ELECTRONIC",
  SET_PRODUCTS_MENCLOTHING: "SET_PRODUCTS_MENCLOTHING",
  SET_PRODUCTS_WOMENCLOTHING: "SET_PRODUCTS_WOMENCLOTHING",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART : "ADD_TO_CART",
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  ADJUST_QTY: "ADJUST_QTY",
  LOAD_CURRENT_ITEM: "LOAD_CURRENT_ITEM" 
};
